import Head from 'next/head'
import Image from 'next/image'


import Navbar from '@/components/navbar'
import Hero from '@/components/hero'
import Cards from '@/components/cards'
import Portfolio from '@/components/portfolio'

import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  


  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Tailwind Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-8 bg-white'>
        <section className='min-h-screen'>
        <Hero/>
        <Cards/>
        <Portfolio/>
        </section>
     
      </main>
    </div>
  )
}
